-- ==============================================================
-- STARK-X (AgriPirate) - Supabase Cloud Database Setup Script
-- ==============================================================
-- Instructions:
-- 1. Go to your Supabase Dashboard: https://supabase.com/dashboard/project/aecywrmehkywbctglsyo
-- 2. Click on "SQL Editor" in the left sidebar (looks like a terminal icon '>_')
-- 3. Click "New Query", paste this entire script, and click "RUN" (green button)
-- ==============================================================

-- 1. Create the SOS Emergency Helpdesk Tickets Table
create table if not exists public.sos_tickets (
    id bigint generated by default as identity primary key,
    name text not null,
    village text not null,
    category text not null,
    description text not null,
    timestamp text not null
);

-- 2. Create Farmer Profiles Table (for farmer metadata)
create table if not exists public.farmers (
    id bigint generated by default as identity primary key,
    email text unique not null,
    name text,
    village text,
    created_at text
);

-- 3. Enable Row Level Security (RLS)
alter table public.sos_tickets enable row level security;
alter table public.farmers enable row level security;

-- 4. Create Security Policies allowing AgriPirate app to read and write
-- (Drop existing policies if any to prevent duplicate errors)
drop policy if exists "Allow public select on sos_tickets" on public.sos_tickets;
drop policy if exists "Allow public insert on sos_tickets" on public.sos_tickets;
drop policy if exists "Allow public select on farmers" on public.farmers;
drop policy if exists "Allow public insert on farmers" on public.farmers;

create policy "Allow public select on sos_tickets" 
on public.sos_tickets for select 
using (true);

create policy "Allow public insert on sos_tickets" 
on public.sos_tickets for insert 
with check (true);

create policy "Allow public select on farmers" 
on public.farmers for select 
using (true);

create policy "Allow public insert on farmers" 
on public.farmers for insert 
with check (true);

-- 5. Insert Sample Live SOS Ticket for testing verification
insert into public.sos_tickets (name, village, category, description, timestamp)
values ('Murugan K.', 'Perundurai, Erode', 'Water Scarcity', 'Groundwater table dropped below 650ft; requesting union borewell geophysics survey.', to_char(now(), 'YYYY-MM-DD HH24:MI'))
on conflict do nothing;

-- 6. Create Marketplace Crops Table (Phase 2 Upgrade)
create table if not exists public.marketplace_crops (
    id bigint generated by default as identity primary key,
    farmer_name text not null,
    phone_whatsapp text not null,
    crop_name text not null,
    quantity_kg numeric not null,
    price_per_kg numeric not null,
    location text not null,
    created_at text not null default to_char(now(), 'YYYY-MM-DD HH24:MI')
);

alter table public.marketplace_crops enable row level security;

drop policy if exists "Allow public select on marketplace_crops" on public.marketplace_crops;
drop policy if exists "Allow public insert on marketplace_crops" on public.marketplace_crops;

create policy "Allow public select on marketplace_crops" 
on public.marketplace_crops for select 
using (true);

create policy "Allow public insert on marketplace_crops" 
on public.marketplace_crops for insert 
with check (true);

-- Sample Marketplace listing
insert into public.marketplace_crops (farmer_name, phone_whatsapp, crop_name, quantity_kg, price_per_kg, location)
values ('Murugan K.', '+91 98765 43210', 'Erode Organic Turmeric (Finger)', 500, 145, 'Perundurai, Erode')
on conflict do nothing;

